## Creating arrays using Lists

In [77]:
import numpy as np

In [78]:
myList =[1,2,3,4,5,6]
np.array(myList)

array([1, 2, 3, 4, 5, 6])

In [8]:
myNestedList=[[1,2,3],[3,4,5],[5,6,7]]
np.array(myNestedList)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [9]:
myList1=[1,3,4]
myList2=[3,4,5]
np.array([myList1,myList2])

array([[1, 3, 4],
       [3, 4, 5]])

# Creating Arrays using Functions

In [10]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
np.arange(4,44,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [82]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [19]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [83]:
np.full((5,5),20.5,dtype=float)

array([[20.5, 20.5, 20.5, 20.5, 20.5],
       [20.5, 20.5, 20.5, 20.5, 20.5],
       [20.5, 20.5, 20.5, 20.5, 20.5],
       [20.5, 20.5, 20.5, 20.5, 20.5],
       [20.5, 20.5, 20.5, 20.5, 20.5]])

In [21]:
np.info(np.full)

 full(shape, fill_value, dtype=None, order='C', *, like=None)

Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acce

In [108]:
x=np.array([3,1,0]) #If any zero is present then give false
np.all(x)# All gives True When no zero is there

False

In [109]:
h=np.array([0,0,0,1])# if any non-zero values is present it give True
np.any(h)#All Values are zeros then Gives False

True

In [24]:
a=np.array([0,2,3,np.nan,np.inf])#nan=not a number,inf=infinite
a

array([ 0.,  2.,  3., nan, inf])

In [25]:
np.isinf(a)

array([False, False, False, False,  True])

In [26]:
np.isnan(a)

array([False, False, False,  True, False])

In [15]:
c=np.array([1+3j,4,4+5j,8,9])
c

array([1.+3.j, 4.+0.j, 4.+5.j, 8.+0.j, 9.+0.j])

In [16]:
np.iscomplex(c)

array([ True, False,  True, False, False])

In [17]:
np.isreal(c)

array([False,  True, False,  True,  True])

# comparison

In [115]:
x=np.array([1,2,3,4])
y=np.array([2,1,3,5])

In [116]:
np.greater(x,y)

array([False,  True, False, False])

In [117]:
np.less(x,y)

array([ True, False,  True,  True])

In [118]:
np.greater_equal(x,y)

array([False,  True, False, False])

In [121]:
np.less_equal(x,y)

array([ True, False,  True,  True])

In [122]:
v=np.identity(6,dtype=int)
print(v)
v.shape

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


(6, 6)

In [126]:
np.random.normal(0,1)

0.0016862935202992203

In [129]:
A=np.arange(10,22).reshape(6,2)
A

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [130]:
v=np.linspace(10,49,11,dtype=int)#Giving 11 elements
v

array([10, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [29]:
np.random.randint(0,11,6) #Gives 6 random integers 

array([4, 1, 7, 3, 9, 2])

# calculations

In [48]:
x=np.array([1,2,3,5])
y=np.array([2,3,5,6])
multiply=x*y

In [49]:
multiply

array([ 2,  6, 15, 30])

In [51]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [52]:
x=np.arange(20,32).reshape(4,3)
print(x)
np.sum(x)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


306

In [53]:
np.sum(x,axis=0)#Columns wise sum

array([ 98, 102, 106])

In [54]:
np.sum(x,axis=1)#rows

array([63, 72, 81, 90])

In [55]:
x=np.array([1,2])#first multiply and then Add
y=np.array([3,4])
np.dot(x,y)

11

In [56]:
np.multiply(x,y)

array([3, 8])

In [57]:
np.outer(x,y)

array([[3, 4],
       [6, 8]])

In [58]:
np.zeros_like(x)

array([0, 0])

In [132]:
np.arange(1,46).reshape(3,5,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])

In [61]:
np.__version__

'1.21.1'

# BroadCasting

In [63]:
newarr=np.arange(10)
newarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
newarr[:]=10

In [65]:
newarr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [69]:
newarr[4:7]=200

In [73]:
newarr

array([ 10,  10,  10,  10, 200, 200, 200,  10,  10,  10])

# copy

In [71]:
copy=newarr.copy()

In [72]:
copy

array([ 10,  10,  10,  10, 200, 200, 200,  10,  10,  10])

In [75]:
copy[:5]=45

In [76]:
copy

array([ 45,  45,  45,  45,  45, 200, 200,  10,  10,  10])

# Sorting

In [32]:
unsorted=np.array([20,10,23,11,40,12])

In [33]:
unsorted.sort()

In [34]:
unsorted

array([10, 11, 12, 20, 23, 40])

In [35]:
type(unsorted)

numpy.ndarray

# Indexing

In [36]:
arr2d=np.arange(25).reshape(5,5)

In [37]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr2d[1][2] 

7

In [133]:
arr2d[:,:3] #arr[row_start:row_end,elemt_start:elemnt_end]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [42]:
arr2d[2:5,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [135]:
arr2d[:2,2:]#start:End of start,Start ofelmt in a  row:end of elmt in a row

array([[2, 3, 4],
       [7, 8, 9]])

# conditional

In [144]:
newArr = np.arange(1,11)

In [145]:
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
newArr[newArr>5]

array([ 6,  7,  8,  9, 10])

In [148]:
newArr[newArr<5]

array([1, 2, 3, 4])

In [149]:
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
newArr[newArr==6]

array([6])